### ISSUE TITLE
Request - Multiple Lambdas in one project start

### ISSUE THREAD

**Issue by nimrodraifer** [ArsenyYankovsky/serverless-rust-starter#1]
Hi,

I believe it would be great for others to see also an example of serverless rust starter that has multiple lambdas within.

Thanks.

**Comment by ArsenyYankovsky** [comment]
Hello, 

Sure, I added two lambdas in the starter.

Basically, to add a new lambda you'd do three things:

- Add a lambda into `functions` section of `serverless.yml`
- Add a description of a new binary into `Cargo.toml`
- Add a new binary into src/bin folder.
